I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day_zero.rpy", line 8, in script call
    call DispositionCalc
  File "game/day_zero.rpy", line 8, in script call
    call DispositionCalc
ScriptError: could not find label 'DispositionCalc'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day_zero.rpy", line 8, in script call
    call DispositionCalc
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/day_zero.rpy", line 8, in script call
    call DispositionCalc
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'DispositionCalc'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.1.1.23060707
DIAR Day 0 Prototype 1.0
Fri Jul  7 23:09:29 2023
