I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/minigames/cleaning_minigame.rpy", line 227, in script
    $ renpy_blur(difference_image, 1.5)
  File "game/minigames/cleaning_minigame.rpy", line 227, in <module>
    $ renpy_blur(difference_image, 1.5)
NameError: name 'renpy_blur' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/minigames/cleaning_minigame.rpy", line 227, in script
    $ renpy_blur(difference_image, 1.5)
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/minigames/cleaning_minigame.rpy", line 227, in <module>
    $ renpy_blur(difference_image, 1.5)
NameError: name 'renpy_blur' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
DIAR Day 0 Prototype 1.0
Tue Aug 29 16:54:47 2023
