I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/map.rpy", line 16, in script
    call screen Office
ScriptError: could not find label 'conv_Poster'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\execution.py", line 953, in run_context
    context.run()
  File "game/map.rpy", line 16, in script
    call screen Office
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'conv_Poster'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.1.1.23060707
DIAR Day 0 Prototype 1.0
Sat Jul  8 12:48:10 2023
